<?php

$productsArray = array(
 array(1,"Signature trench khaki", "Totême’s signature trench cut from a durable cotton blend. It’s shaped to a relaxed silhouette with a lapel collar, double-breasted fastening, belted cuffs, slanting side pockets, and a monogram lining. Wear open or closed with the matching cap to the park.", 6500, "outerwear"),
 array(2,"Army jacket olive", "Army-inspired jacket cut from a Japanese cotton fabric. It’s shaped to an oversized silhouette with a concealed button fastening, a nipped-in waist at the back, buttoned cuffs, and utility pockets with built-in slanting side pockets. Dress up with trousers and a silk scarf this spring.", 4000, "outerwear"),
 array(3,"Signature wool cashmere coat black", "Annecy coat, Totême’s signature coat hand-stitched from a double wool cashmere fabric that has been gently brushed for softness. It’s designed for an oversized fit and shaped to a relaxed silhouette with a draped collar, drop shoulders, and an open front which makes it perfect for layering. The coat is finished with inseam pockets and side slits. Layer over a top in fall and knit in winter, adding Double wool cashmere scarf to complete the look.", 8000, "outerwear"),
 array(4,"Quilted jacket black", "Dublin jacket, Totême's quilted jacket cut from a recycled yarn fabric. It’s designed for an oversized fit and shaped to a boxy silhouette with a round neck, drop shoulders, press buttons, side pockets, and a rounded hem that is longer at the back, creating a chic A-line shape in profile. Layer over a turtleneck or underneath Lambswool bib on your daily commute.", 4000, "outerwear"),
 array(5,"Army leather jacket black", "Army-inspired jacket cut from supple double-sided leather. It’s shaped to an oversized silhouette with a lapel collar, a zipper fastening, slits at the sleeves, utility pockets, and raw edges. A transeasonal investment piece for your everyday uniform.", 16000, "outerwear"),
 array(6,"Polo shirt knit black", "Polo shirt knit cut from a sheer ribbed fabric. It’s shaped to a relaxed silhouette with a polo shirt collar with monogram buttons, drop shoulders, wide sleeves, and a straight hem. Team with Rib knit maxi skirt in the same fabric for days off in the city.", 2400, "sweaters"),
 array(7,"Boxy alpaca knit black", "Biella knit, Totême's boxy knit cut from a hairy alpaca blend fabric. It’s shaped to a wide, relaxed silhouette with a ribbed round neck and drop shoulders. Wear with mules and trousers to dinner or leggings on the couch.", 3800, "sweaters"),
 array(8,"Signature stripe turtleneck light sand stripe", "Relaxed turtleneck cut from the softest merino wool plated with cotton. It’s shaped to a wide silhouette that creates a natural drape at the front and has a ribbed turtleneck, drop shoulders, wide sleeves, side slits, and a cropped length. Layer over denim on weekdays with the turtleneck undone.", 3900, "sweaters"),
 array(9,"Lambswool knit cardigan creme", "Fisherman knit cardigan cut from a ribbed lambswool fabric. It’s shaped to a slim silhouette with a v-neck, wide sleeves, twisted seams along the sides, and a straight hem. Style with denim and a belt at the waist for a chic everyday look.", 3600, "sweaters"),
 array(10,"Merino wool zip knit black", "Zipper knit cut from a double-knitted merino wool fabric. It’s shaped to a regular silhouette with a ribbed turtleneck collar with a monogram zipper, raglan sleeves, ribbed cuffs, and a straight ribbed hem. Layer over a tee and denim look on weekdays and leggings on weekends.", 2600, "sweaters"),
 array(11,"Monogram silk PJ bottoms ivory", "Fluid trousers cut from a thick silk twill fabric. They are shaped to a relaxed silhouette with an elasticated waistband, an all-over monogram embroidery, side pockets, and straight long legs. Coordinate with Monogram silk pj top on vacation.", 4800, "trousers"),
 array(12,"Pine suit trousers black", "Suit trousers cut from a responsibly sourced viscose fabric. They are shaped to a wide silhouette with a high waist, a zip and hook fastening, slanting side pockets, back patch pockets, sewn front pleats, and long legs. Team with Pine suit waistcoat and Pine suit blazer to special occasions.", 3700, "trousers"),
 array(13,"Zip leggings black", "Everyday leggings cut from a thick responsibly sourced viscose fabric. They are shaped to a fitted silhouette with an elasticated high waist and flattering slim legs that are finished with zipped hems for optional slits. Wear at home or on the go (and not to workout).", 1400, "trousers"),
 array(14,"Silk satin slacks black", "Slacks cut from a fluid silk satin fabric. They are shaped to a relaxed silhouette with an elasticated waistband and straight long legs. Wear this Holiday season with slippers in the morning and mules to dinner.", 3200, "trousers"),
 array(15,"Stretch linen slacks city white", "Relaxed trousers cut from a stretchy linen blend fabric. They are shaped to a wide silhouette with a high waist, an elasticated waistband, slanting side pockets, and a slightly cropped length. Wear over your swimsuit to the pool, style with a tee to work, or coordinate with Half button linen shirt to dinner.", 2200, "trousers"),
 array(16,"Stretch linen dress black", "Maxi dress cut from an Italian stretch linen blend fabric. It’s shaped to an A-line silhouette with a round neck, short rounded sleeves, a concealed zipper fastening at the back, top stitchings, and a maxi skirt that ends just above the ankles. Wear on its own with sneakers this summer.", 3900, "dresses"),
 array(17,"Crinkled silk slip dress off-white", "Crinkled dress cut from a matte habutai silk fabric. It’s shaped to a straight silhouette with slim spaghetti straps that create a square neck, and is lined at the chest. The dress ends mid-leg. The crinkled finish makes it perfect for packing – coordinate with Crinkled silk scarf on vacation.", 4900, "dresses"),
 array(18,"Spaghetti strap smock dress black", "Midi dress cut from a stretchy smocked silk blend fabric. It’s shaped to a fitted silhouette from the waist up with spaghetti straps that form a square neck and a smocked body. Below the waist, the dress falls into a fluid layered skirt that is lined and ends just above the ankles. Team with flats in daytime and mules at night.", 5000, "dresses"),
 array(19,"Tea length smock dress", "Cocktail dress cut from a lustrous cotton blend fabric. It’s shaped to a fitted silhouette from the waist up with an elasticated square neck, draped details at the shoulders, and a smocked body. Below the waist, the dress falls into a draped A-line skirt that ends mid-leg. Team with flats or heels for special occasions this summer.", 3800, "dresses"),
 array(20,"Heavy metal dress", "Knitted maxi dress cut from a sheer metallized fabric. It’s shaped to a relaxed straight silhouette with a round neck, wide sleeves, and a full-length skirt. The dress is fully lined. Slip into flats and you're dressed for dinner.", 4600, "dresses")
);